services:
  frontend:
    build: frontend/.
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build: backend/.
    ports:
      - 3001:3001
    volumes:
      - ./backend/google-cloud.json:/app/google-cloud.json
