services:
  frontend:
    build: frontend/.
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build: backend/.
    environment:
      - NEXT_PUBLIC_WEBSOCKET_URL=http://backend:3001
    ports:
      - 3001:3001
