services:
  frontend:
    build: frontend/.
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: always

  backend:
    build: backend/.
    ports:
      - 3001:3001
    volumes:
      - ./google-cloud.json:/app/google-cloud.json
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
  tigergraph_data:

  tigergraph:
    image: tigergraph/tigergraph:3.10.0
    ports:
      - 9000:9000
      - 14022:22
      - 14240:14240
    volumes:
      - tigergraph_data:/home/tigergraph/tigergraph/data
    restart: always
